### ISSUE TITLE
[electron] unable to build electron example app

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse/theia-cpp-extension#28]
**Description**

I am unable to build the `electron-app` for the repository.
The command fails when attempting to perform `yarn rebuild:electron`.

**Steps to Reproduce**
1. clone the repository
2. perform `yarn` at the root of the repository
3. perform `yarn rebuild:electron` (the command fails)

**Additional Information**

```
yarn run v1.15.2
$ theia rebuild:electron
Processing @theia/node-pty
Processing nsfw
Processing find-git-repositories
⠋ Searching dependency treeUncaught Exception:  Error: Could not detect abi for version 3.1.8 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
Error: Could not detect abi for version 3.1.8 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/evinfug/theia-workspace/theia-cpp-extension/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/home/evinfug/theia-workspace/theia-cpp-extension/node_modules/electron-rebuild/lib/src/rebuild.js:64:28)
    at rebuildWithOptions (/home/evinfug/theia-workspace/theia-cpp-extension/node_modules/electron-rebuild/lib/src/rebuild.js:316:23)
    at Object.doRebuild [as rebuild] (/home/evinfug/theia-workspace/theia-cpp-extension/node_modules/electron-rebuild/lib/src/rebuild.js:323:16)
    at Object.<anonymous> (/home/evinfug/theia-workspace/theia-cpp-extension/node_modules/electron-rebuild/lib/src/cli.js:114:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/evinfug/theia-workspace/theia-cpp-extension/node_modules/electron-rebuild/lib/src/cli.js:5:58)

```

**Comment by marcdumais-work** [comment]
I think `yarn.lock` is getting in the way, by forcing an older Theia version being pulled in this example app.
